# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='name')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='quantity')),
                ('notes', models.CharField(blank=True, max_length=140, null=True, verbose_name='note')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='instruction')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('serving_qty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='serving qty')),
                ('serving_qty_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='serving qty name')),
                ('prep_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='prep time')),
                ('prep_time_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='prep time name')),
                ('cook_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cook time')),
                ('cook_time_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='cook time name')),
                ('passive_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='passive time')),
                ('passive_time_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='passive time name')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipe.Ingredient', verbose_name='ingredients')),
                ('instructions', models.ManyToManyField(related_name='recipes', to='recipe.Instruction', verbose_name='instructions')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Unit', verbose_name='unit'),
        ),
    ]
