# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20160110_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='ingredient'),
        ),
    ]
