# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20160110_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='servings'),
        ),
    ]
