# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20160110_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['pk']},
        ),
    ]
